In [1]:
import sys
print(sys.version)

3.6.8 |Anaconda custom (64-bit)| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]


In [2]:
import numpy as np

In [3]:
A = 2*np.eye(3)
print(A)

[[ 2.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  2.]]


In [4]:
B = np.linalg.inv(A)
print(B)

[[ 0.5  0.   0. ]
 [ 0.   0.5  0. ]
 [ 0.   0.   0.5]]


In [5]:
A=np.array([[1, 1],[2, 2]])
B=np.array([[0, 1],[0, 0]])
print(np.dot(A,B))
print(A.dot(B))

[[0 1]
 [0 2]]
[[0 1]
 [0 2]]


In [6]:
print(np.zeros((3,3)))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [7]:
for i in range(10):
    print(i!=5)

True
True
True
True
True
False
True
True
True
True


In [8]:
np.sqrt(12*np.pi)

6.139960247678931

In [9]:
np.pi

3.141592653589793

In [10]:
A = np.array([1+1j, 2-3*1j])
print(A*A)

[ 0. +2.j -5.-12.j]
